---
branch: master
# check:
#  - CKV_DOCKER_1
compact: true
directory:
  - ./
  # - iac_input_files
  # - aws_cfn_files/EC2
# docker-image: sample-image
# dockerfile-path: Dockerfile
# download-external-modules: true
# evaluate-variables: true
# external-checks-dir:
external-checks-git:
  #- https://github.com/sun1l-aries/checkov_custom_policies.git//custom_checks
  #- https://gitlab.cloud-oss.libgbl.biz/cloud-security/checkov_custom_policies.git//custom_checks
# - sample-dir
# external-modules-download-path: .external_modules
# framework: cloudformation,terraform
framework:
  # - cloudformation
  - terraform
  - cloudformation
# no-guide: true
output: sarif
# quiet: true
# repo-id: bridgecrew/sample-repo
skip-check:
  - CKV2_AWS_12
  - CKV2_AWS_19
  - CKV_AWS_144
# skip-fixes: true
# skip-framework: dockerfile
# skip-suppressions: true
# soft-fail: true
